#!/bin/bash

SCRIPTDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $SCRIPTDIR/common.sh

require ubinize "Please install mtd-utils"
require img2simg "Please install fastboot-utils"

# build the UBI image
prepare_ubi() {
  local ubi=$1
  local ubifs="$2"
  local nandtype="$3"
  local maxlebcount="$4"
  local eraseblocksize="$5"
  local pagesize="$6"
  local subpagesize="$7"

  local tmpdir=`mktemp -d -t chip-ubi-XXXXXX`
  local ubicfg=$tmpdir/ubi.cfg
  local sparseubi="${ubi}.sparse"
  local mlcopts=""

  if [ -z $subpagesize ]; then
    subpagesize=$pagesize
  fi

  if [ "$nandtype" = "mlc" ]; then
    lebsize=$((eraseblocksize/2-$pagesize*2))
    mlcopts="-M dist3"
  elif [ $subpagesize -lt $pagesize ]; then
    lebsize=$((eraseblocksize-pagesize))
  else
    lebsize=$((eraseblocksize-pagesize*2))
  fi

  echo "[rootfs]
mode=ubi
vol_id=0
vol_type=dynamic
vol_name=rootfs
vol_alignment=1
vol_flags=autoresize
image=$ubifs" > $ubicfg

  ubinize -o $ubi -p $eraseblocksize -m $pagesize -s $subpagesize $mlcopts $ubicfg
  img2simg $ubi $sparseubi $eraseblocksize
  rm -rf $tmpdir
}

usage() {
  echo -e "\n\
  usage: $(basename $0) [options] INPUTFILE\n\
\n
  options:\n\
    -N FILENAME		- read nand configuration from FILENAME\n\
    -d OUTPUTDIR        - write file to OUTPUTDIR (default: .)\n\
    -o OUTPUTFILE       - write to OUTPUTFILE (default: $outputdir/chip-$NAND_EBSIZE-$NAND_PSIZE.ubi)n\
    -h, --help          - show this help\n\
\n"
  exit 1
}


while getopts ":N:d:o" o; do
    case "${o}" in
        N)
	    read_nand_config "${OPTARG}"
            ;;
        o)
            outputfile=${OPTARG}
            ;;
        d)
            outputdir=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

outputdir="${outputdir:-.}"
outputfile="${outputfile:-$outputdir/chip-$NAND_EBSIZE-$NAND_PSIZE.ubi}"
inputfile="$1"

prepare_ubi "${outputfile}" "${inputfile}" $NAND_TYPE $NAND_MAXLEB_COUNT $NAND_ERASE_BLOCK_SIZE $NAND_SUBPAGE_SIZE

